adding the continue-on-error: true

diff --git a/.github/workflows/statusCheck.yaml b/.github/workflows/statusCheck.yaml
--- a/.github/workflows/statusCheck.yaml
+++ b/.github/workflows/statusCheck.yaml
@@ -1,5 +1,4 @@
 name: Status Check Functions on workflow
-
 on:
   workflow_dispatch:
 
@@ -42,10 +41,27 @@ jobs:
         if: cancelled()
         run: echo '⛔ Cancelled - This runs only if job is cancelled manually'
 
-  skipped-job:
-    needs: failure-job
-    if: success()  # this will be false because failure-job fails
+    skipped-job:
+      needs: failure-job
+      if: success()  # this will be false because failure-job fails
+      runs-on: ubuntu-latest
+      steps:
+        - name: step 1. This will be skipped
+          run: echo '🚫 Skipped - This step will be skipped because it depends on failure-job success which got failed'
+
+  skipping-fail-with-continue-on-error-job:
     runs-on: ubuntu-latest
     steps:
-      - name: step 1. This will be skipped
-        run: echo '🚫 Skipped - This step will be skipped because it depends on failure-job success which got failed'
+      - name: step 1. sleeping for 20 seconds
+        run: sleep 20
+      - name: step 2. intentionally quiting the job
+        id: quitingStep2
+        continue-on-error: true
+        run: exit 1
+      - name: step 3. Calling failure() method to check if job failed
+        if: failure() && steps.quitingStep2.conclusion == 'failure'
+        run: |
+          echo '✅ Runs is Success even tough  steps.quitingStep2.conclusion is failure'
+      - name: step 4. checking for Always() method
+        if: always()
+        run: echo '🟡 Always runs regardless of job result'
diff --git a/src/main/java/org/gitHubActionsPractise/p11_statusCheck/statusCheck.yaml b/src/main/java/org/gitHubActionsPractise/p11_statusCheck/statusCheck.yaml
--- a/src/main/java/org/gitHubActionsPractise/p11_statusCheck/statusCheck.yaml
+++ b/src/main/java/org/gitHubActionsPractise/p11_statusCheck/statusCheck.yaml
@@ -48,3 +48,20 @@ jobs:
       steps:
         - name: step 1. This will be skipped
           run: echo '🚫 Skipped - This step will be skipped because it depends on failure-job success which got failed'
+
+  skipping-fail-with-continue-on-error-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: step 1. sleeping for 20 seconds
+        run: sleep 20
+      - name: step 2. intentionally quiting the job
+        id: quitingStep2
+        continue-on-error: true
+        run: exit 1
+      - name: step 3. Calling failure() method to check if job failed
+        if: failure() && steps.quitingStep2.conclusion == 'failure'
+        run: |
+          echo '✅ Runs is Success even tough  steps.quitingStep2.conclusion is failure'
+      - name: step 4. checking for Always() method
+        if: always()
+        run: echo '🟡 Always runs regardless of job result'
